require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CurvesController do

  # This should return the minimal set of attributes required to create a valid
  # Curve. As you add validations to Curve, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "market" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CurvesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all curves as @curves" do
      curve = Curve.create! valid_attributes
      get :index, {}, valid_session
      assigns(:curves).should eq([curve])
    end
  end

  describe "GET show" do
    it "assigns the requested curve as @curve" do
      curve = Curve.create! valid_attributes
      get :show, {:id => curve.to_param}, valid_session
      assigns(:curve).should eq(curve)
    end
  end

  describe "GET new" do
    it "assigns a new curve as @curve" do
      get :new, {}, valid_session
      assigns(:curve).should be_a_new(Curve)
    end
  end

  describe "GET edit" do
    it "assigns the requested curve as @curve" do
      curve = Curve.create! valid_attributes
      get :edit, {:id => curve.to_param}, valid_session
      assigns(:curve).should eq(curve)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Curve" do
        expect {
          post :create, {:curve => valid_attributes}, valid_session
        }.to change(Curve, :count).by(1)
      end

      it "assigns a newly created curve as @curve" do
        post :create, {:curve => valid_attributes}, valid_session
        assigns(:curve).should be_a(Curve)
        assigns(:curve).should be_persisted
      end

      it "redirects to the created curve" do
        post :create, {:curve => valid_attributes}, valid_session
        response.should redirect_to(Curve.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved curve as @curve" do
        # Trigger the behavior that occurs when invalid params are submitted
        Curve.any_instance.stub(:save).and_return(false)
        post :create, {:curve => { "market" => "invalid value" }}, valid_session
        assigns(:curve).should be_a_new(Curve)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Curve.any_instance.stub(:save).and_return(false)
        post :create, {:curve => { "market" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested curve" do
        curve = Curve.create! valid_attributes
        # Assuming there are no other curves in the database, this
        # specifies that the Curve created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Curve.any_instance.should_receive(:update_attributes).with({ "market" => "MyString" })
        put :update, {:id => curve.to_param, :curve => { "market" => "MyString" }}, valid_session
      end

      it "assigns the requested curve as @curve" do
        curve = Curve.create! valid_attributes
        put :update, {:id => curve.to_param, :curve => valid_attributes}, valid_session
        assigns(:curve).should eq(curve)
      end

      it "redirects to the curve" do
        curve = Curve.create! valid_attributes
        put :update, {:id => curve.to_param, :curve => valid_attributes}, valid_session
        response.should redirect_to(curve)
      end
    end

    describe "with invalid params" do
      it "assigns the curve as @curve" do
        curve = Curve.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Curve.any_instance.stub(:save).and_return(false)
        put :update, {:id => curve.to_param, :curve => { "market" => "invalid value" }}, valid_session
        assigns(:curve).should eq(curve)
      end

      it "re-renders the 'edit' template" do
        curve = Curve.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Curve.any_instance.stub(:save).and_return(false)
        put :update, {:id => curve.to_param, :curve => { "market" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested curve" do
      curve = Curve.create! valid_attributes
      expect {
        delete :destroy, {:id => curve.to_param}, valid_session
      }.to change(Curve, :count).by(-1)
    end

    it "redirects to the curves list" do
      curve = Curve.create! valid_attributes
      delete :destroy, {:id => curve.to_param}, valid_session
      response.should redirect_to(curves_url)
    end
  end

end
